### ISSUE TITLE
Is it a good idea to have graph visualization of netlist extracted from kfactory?

### ISSUE THREAD

**Issue by Hsuan-Tung** [gdsfactory/kfactory#154]
I followed the example of netlist extraction from this [PR](https://github.com/gdsfactory/kfactory/pull/146) and post-processed the netlist to generate this graph visualization with powerful [graph-tool](https://graph-tool.skewed.de/static/doc/quickstart.html). The results are shown as follows. GDS: 

![image](https://github.com/gdsfactory/kfactory/assets/26587780/9aa120b6-06c6-4e22-889f-00c592ff0a7a)

Graph visualization of Netlist:
![image](https://github.com/gdsfactory/kfactory/assets/26587780/4f56c497-630d-49a6-a20a-0aacf8ea7223)
Or:
![image](https://github.com/gdsfactory/kfactory/assets/26587780/1de444a3-9d14-42af-b559-95ba9e3afea2)

Wonder if we would like to implement something like above?

**Comment by drinwater** [comment]
Hi Hsuan-Tung,

This is very cool, it'd be nice ton have smth like this in kfactory. Is this on any branch? 


-SkandanC

**Comment by sebastian-goeldi** [comment]
I agree with Skandan, this would be very cool to display it. I think this could be very powerful.

**Comment by Hsuan-Tung** [comment]
Okay, I will make some more examples and push to another branch called `netlist_graph` once it's done.

**Comment by joamatab** [comment]
yes, looking forward to having this

**Comment by joamatab** [comment]
plotly also has some nice graph tools

https://gdsfactory.github.io/gdsfactory/notebooks/_4_gdsfactory.html

**Comment by sebastian-goeldi** [comment]
Small update:

![image](https://github.com/gdsfactory/kfactory/assets/44963764/bacc900b-bec6-4eda-85c6-8267d5091590)

It's for now on the branch `better-netlists`

Instead of netlist objects kfactory can now produce `LayoutToNetlist` objects, which are a coupled netlist + layout object, i.e. the netlist can be visually inspected and has some awareness of the layout. What doesn't work yet is the colorization and showing of the Nets (which the klayout internal netlist extractor can).

**Comment by joamatab** [comment]
Can you make a PR for this?

**Comment by sebastian-goeldi** [comment]
Are we doing anything with this? I would say `graph-tool is a nogo since it's only available through conda-forge
