### ISSUE TITLE
Multithreading & distributed operations

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/kfactory#68]
KLayout allows a way to split a layout into tiles that are processed in parallel via the [TilingProcessor](https://www.klayout.de/doc/code/class_TilingProcessor.html#method44)

In parallel, there are now very powerful general-purpose packages such as [Ray](https://www.ray.io/ray-core) to seamlessly distribute Python code to multiple local cores, to clusters, to cloud, if one were to "tile" their layout themselves.

Is there an agreed-upon plan to introduce some form of parallelism into kfactory? This could accelerate booleans, fill, DRC, etc...

**Comment by sebastian-goeldi** [comment]
We have to make sure first that it is possible in the python module. Some of these things are not available in the python code. E.g. @klayoutmatthias was not sure whether the mutex for the tilingprocessor is available. Also, I am not sure you can use multithreading for booleans (I mean you can submit each job separately e.g. if you want booleans for multiple layers)

**Comment by klayoutmatthias** [comment]
The tiling process has a mutex (https://github.com/KLayout/klayout/blob/c6bfb03a180d8f441e8b5c0228c1778689ee780a/src/db/db/dbFillTool.cc#L281), so using the fill tool inside the tiling processor is safe.

Creating the fill cell is a one time action, so that can happen in the main thread. When you build your own threading around the other available features, you need to be very careful with accessing common objects - specifically the layout object. Reading from multiple threads is safe, reading and writing from different threads or writing from multiple threads isn't. Normally, even inserting shapes into different layers / cells from different threads isn't, because bounding boxes or the cell graph are tracked globally. You can mitigate the effect, but putting your whole code into a `start_update ... end_update` block (https://www.klayout.de/doc-qt5/code/class_Layout.html#method138). This will disable most of the internal interactions and make things thread safer.

Flat region objects are safe when allocated for a specific thread, they are a good way to store a thread's local data. Deep-mode region objects (sharing a common DeepShapeStorage object) are safe in terms of reading and writing, but not in terms of creation - that should happen in the main thread / mutex locked.

But after all, I'm talking **kernel threads** here. Not the thing that CPython calls threads. These are implicitly locked by the GIL and AFAIK do not even execute on different cores. So whatever you do in these threads should not matter to KLayout database objects. Kernel threads are an entirely different thing. They are not synchronized, may execute on different cores and in general you need to be super careful with them.

Matthias

**Comment by sebastian-goeldi** [comment]
Thanks Matthias.

Perfect, then it is as I thought.

Generally we aren't using deep shape storage (yet), so no concerns yet.

As for thread safety my idea is the following:
The cell decorator would basically "create" the cell as a future and then dispatch a job (I assume ray e.g. uses multiple true kernel threads, not the python "threads" ;)). This would allow us to e.g. calculate multiple regions that are expensive in parallel.

If any other cell wants to actually do something except the call to create it, it will just wait until the function is evaluated.

This will help us especially on the chip level to speed it up considerably. We at PsiQ e.g. have some components that are essentially very long snakes that need a cladding that should be in a cladding material that should be as accurate as possible. I would like to do that with minkowski sums (already doing that but it takes ~5-10s per cell). So if we can do it in parallel (which I am now reasonably sure that we can after your comment ;) ), that would cut down the computations time of minutes to seconds assuming there are enough cores available.

**Comment by sebastian-goeldi** [comment]
@simbilod is the current implemention good enough? I think theoretically we could add multi-threading/processing to the decorator, but I am not sure this is what you wanted to achieve with this?

**Comment by simbilod** [comment]
yes I think the KLayout scripts are good for  what I had in mind, delayed execution and whatnot can come later!
