### ISSUE TITLE
gdsfactory/kfactory compatibility

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#81]
Here are some issues that would be great to add to kfactory to enable gdsfactory compatibility with kfactory backend

- [ ] gdsfactory allows to define ports with `None` angle for electrical ports.

**Comment by sebastian-goeldi** [comment]
> gdsfactory allows to define ports with None angle for electrical ports.

Can't do that. I guess we can relax the constructor to just set it to 0 by default. Since ports are based on transformations, they need an angle. I think it would be better to have something like `ignore_angle` to `connect_elec`, but it makes it a bit funny because the route will just become a straight or corner, meaning you don't really need a connect function.

**Comment by joamatab** [comment]
it's that way so that it can start with any angle

**Comment by sebastian-goeldi** [comment]
Yeah, I understand why it's there. I am saying we can't do it out of the box :P.

I see two options:

1. We make a specifically electircal port (or rather pin), which is a special (sub) type of port that is based on a vector instead of transformation (this would mean it's incompatible with optical ports, but I think that's fine)

2. We set a flag on the port indicating that the port actually doesn't care about the angle.

1) is cleaner but has some implications. 2) is easier to implement.

**Comment by sebastian-goeldi** [comment]
Also, now that I think about it, i believe `connect_elec` doesn't actually really care about the orientation (as long as start/end_straight are 0). I believe the resulting polygon will look the same
