### ISSUE TITLE
add gdsfactory convenient functions

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#92]
TODO:

- [x] inst.xmin = 0 `setter` (xmin, xmax, ymin, ymax, x, y)
- [x] inst.mirror(), inst.mirror_x(), inst_mirror_y()
  - mirror_x mirrors over an x axis, for example x=0
  - mirror_y mirrors over a y axis , for example y=0
- [x] inst.rotate()
- [ ] cell.add_polygon(points, layer)
- [ ]  add_label(text, layer)

**Comment by sebastian-goeldi** [comment]
What's the difference between mirror_x/y and mirror? I mean sure, we can add them, but logically speaking everything is one mirror flag, the others are combinations of rotations + mirror.

Also keep in mind, align will break any mirror shenanigans you do before.

**Comment by sebastian-goeldi** [comment]
Regarding `add_polygon`: it is really bad if you consider all the other geometrical operations, it would be a completely different flow. I am ok to add something like `(d)polygon_from_2darray`

**Comment by sebastian-goeldi** [comment]
`x/ymin/max` also modify the bbox in gdsfactory, right? If yes, this will be super confusing, bcause we can't do that in klayout

**Comment by sebastian-goeldi** [comment]
@joamatab  could you elaborate how you want the above comments implemented?

**Comment by sebastian-goeldi** [comment]
mirror_x/mirror_y yes, absolutely, let's add them.

mirror, I am not sure there is a huge need for this and it would kind of require quite a bit of coding. Plus it can be done by a complex transformation, so I think it's okay not to have this?

add_polygon/text, I think we should avoid because we should teach people how to use shapes in Klayout, as there are other legit shapes in Klayout that can be used like edge/box/point/vecotr etc. Additionally the footprint of add_polygon is very dangerous for kfactory `c.add_polygon(..., 5)` is legal in gdsfactory (afaik), but completely illegal in Klayout unless you created at least 6 layers (with default constructor). Same for add_label.

I think it's reasonable to expect to learn `c.shapes(layer_index).insert` instead of the add_polygon. Plus it avoids doing the conversion of array to point array miltiple times; in kfactory you can add a polygon multiple times on different layers witjout having to recreate a new polygon every time

I am totally in favor of adding something like `kf.polygon_from_array` and its floating point equivalent which would give you the polygon without having to go through creating points yourself.

**Comment by joamatab** [comment]
sounds good, `kf.polygon_from_array` sounds good to me

**Comment by joamatab** [comment]
How about the labels?

How about `KCell.add_label(text='hi, position=(3,0), layer=LAYER.WG)

**Comment by sebastian-goeldi** [comment]
I think the danger of people passing a layer_number where we would expect a layer_index is too great. I would opt for #140 and document to use `c.shapes(LAYER.WG).insert(kf.kdb.Text("hello",x,y)` instead. And with this way we also directly get the floating/dbu parts for free, without having to worry about converaions.

**Comment by Hsuan-Tung** [comment]
Agree with @sebastian-goeldi on `add_polygon` and `add_label`. Besides these functions, I have reproduced some other gdsfactory functions in kfactory such as `netlist_to_component`  etc. I wonder if we would like to have it inside kfactory.

**Comment by joamatab** [comment]
that would be great

**Comment by Hsuan-Tung** [comment]
> that would be great

The netlist_to_component is currently on the branch, `convenient_func`.

**Comment by sebastian-goeldi** [comment]
@joamatab can we consider this as fixed?

**Comment by joamatab** [comment]
Yes, thank you Sebastian
