### ISSUE TITLE
improve names

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#97]
coming from gdsfactory I find some kfactory names confusing, How about renaming some of the names to more intuitive?

- align. Align is used in powerpoint and other software to do something else. I prefer `connect`, `join`, or `mate`. My preference would be `connect` 
- `connect`. we are not connecting things. we are routing things. in gdsfactory we call this `get_route`, but maybe we should follow [phidl](https://phidl.readthedocs.io/en/latest/tutorials/routing.html) on this and just use route. I like the idea of 
   - connect_elec --> route_electrical
   - connect -> route
   - route_bundle 
   - route_path_length_match

**Comment by sebastian-goeldi** [comment]
1) `connect` is a lie though. It is an alignment in the sense of powerpoint though. It arranges both ports in a straight line, so it is in this sense an alignment. The functionality doesn't do anything you imply with your names. `connect/join/mate` implies if I connect `b` to `a` and then move `a` that `b` is moved along with `a`, which it doesn't. There are requests for this functionality, but there isn't atm.

2) fair point. But `get_route` means I get a roite, but the function actually places it into a cell already. And having a "virtual" route is tricky in klayout. It can be done, but would have some implication and limitations. Maube we can call it `place_route`? The actual `get_route` is happening in the manhattan functions (by default)

**Comment by joamatab** [comment]
1. i like connect, merge/join would imply that the connection remains :) align sounds more of align_x or align_y
2. `place_route` sounds good to me

**Comment by sebastian-goeldi** [comment]
Well, it's just that it's not only x/y, it also aligns rotation & mirror. So, I think it's jot that far off.

The problem with connect is very simple. As your own sentence proves, there is a very small jump from connect to connection. And it doesn't help that in gdsfactory, your very first sentence introducing [connect](https://gdsfactory.github.io/gdsfactory/notebooks/00_geometry.html#connect-ports) says 

> Components can have a “Port” that allows you to connect ComponentReferences together like legos.

When you "connect" two blocks, they stick together, which is neither the case in gdsfactory, nor kfactory. So your own documentation works against your own argumentation here. And this taints the whole argument for using "connect". I also liked the name connect, until I had to have this exact conversation with new users of kfactory 2 or 3 times (with the roles reversed). @gdspaul can sing a song about this by now I think.

**Comment by joamatab** [comment]
i think `connect` is the best name,
align does not make any sense to me :)
Align is used in powerpoint to align X or Y, right side or left side


if we want to imply things connected we can create something like `merge`

**Comment by sebastian-goeldi** [comment]
but you are doing exactly that, you are aligning x, y, angle and mirror flag. 

Tbh I am fine with anything but `connect/merge/join`, because you aren't doing anything to bind the two instances together, you are just doing an automatic move/transformation of `a` to `b_port`

**Comment by joamatab** [comment]
How about `mate`?

changing from `connect` would make any gdsfactory users confused

**Comment by sebastian-goeldi** [comment]
`mate` has the exact same problem as the others, it implies the two pieces are a couple afterwards.

The inherent problem is this, and this imo stays the same for all the suggestions you had if we project to the building blocks sentence:

```
                                                                                               move    ┌─^──^──^──^──^──^──^──^─┐
                                                                                         ─────────────►│                        │
       b.connect(pname1, a.ports[pname2])                                                              │                        │
                                                                                                       │                        │
                                                                                                       │         B              │
                                                                                                       │                        │
                                                                                                       │                        │
               ┌─^──^──^──^──^──^──^──^─┐      move B building block                    ┌─^──^──^──^──^└─────────┬──────────────┘
               │                        │     ────────────────────────────►             │                        │
               │                        │                                               │                        │
               │                        │                                               │                        │
               │         B              │                                               │          A             │
               │                        │                                               │                        │
               │                        │                                               │                        │
┌─^──^──^──^──^└─────────┬──────────────┘                                   +           └────────────────────────┘
│                        │
│                        │
│                        │
│          A             │                                                                             ┌─^──^──^──^──^──^──^──^─┐
│                        │             │                                                               │                        │
│                        │             │                                                               │                        │
+────────────────────────┘             │                                                      move     │                        │
                                       │                                                 ─────────────►│          B             │
▲                                      │                                                               │                        │
│                                      │                                                               │                        │
│                                      │                                    ┌─^──^──^──^──^──^──^──^─┐ └────────────────────────┘
│                                      │                                    │                        │
│origin                                │                                    │                        │
                                       │                                    │                        │
                                       │                                    │          A             │
                                       │                                    │                        │
                                       │ move B gdsfactory after connect    │                        │
                                       └──────────────────────────────────► +────────────────────────┘
```

Until 0.7.0 there is a deprecation warning for `Instance.connect` I am also fine leaving that one in for longer and we can also link to this discussion. I think we should write a documentation for switching over from gdsfactory anyway, as there are multiple changes that are not intuitive.

**Comment by joamatab** [comment]
yes, i understand the implication on `connect` but i think is the best term and you cannot expect things to remain connected if you force other connections between blocks

I don't like when software packages invent new terms, specially if the new term is not intuitive (like align). For us which use the package daily is not a problem, but new users are going to have a hard time understanding why `align` is supposed to connect two elements :)



@HelgeGehring
@amccaugh
@tvt153

BTW, what package do you use to make the ASCII drawings?

**Comment by sebastian-goeldi** [comment]
But that's exactly my point. When people read `connect`, they think it's "connected" afterwards. Everybody that I introduced to kfactory (and some of them used gdsfactory before but still thought this way) was confused because connect isn't creating a connection. I don't care about the name, but for new users it's super confusing, especially if you make the comparison to legos in the first sentence, because legos don't behave like this at all. For @gdspaul it only made sense after I said "It's more like a jenga tower in zero G"

Regarding ascii: https://github.com/lewish/asciiflow / https://asciiflow.com

**Comment by gdspaul** [comment]
Sebastian expresses my position on "connect" very well at this point.  😊

That being said, I saw another layout package the other day that talks about "pinning" components.  It's ok for names to be different.  The reason to not use connect in kf is because whatever that function was doing was definitely NOT "connecting" things.  Since kf is a less established project it's less painful to experiment with new names--the privilege of having fewer users at the beginning.

My dream, as Sebastian has patiently listened to over and over, is a superior connect function that does what it sounds like it does: graph connection.  Then it can only be broken by "disconnect." Polygon placement is not the most interesting part.

How about gf is gf and kf is kf?  Opinions can differ about naming.  They aren't the same package.

Sent from my iPhone

On May 7, 2023, at 10:27 AM, sebastian-goeldi ***@***.******@***.***>> wrote:


[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

But that's exactly my point. When people read connect, they think it's "connected" afterwards. Everybody that I introduced to kfactory (and some of them used gdsfactory before but still thought this way) was confused because connect isn't creating a connection. I don't care about the name, but for new users it's super confusing, especially if you make the comparison to legos in the first sentence, because legos don't behave like this at all. For @gdspaul<https://github.com/gdspaul> it only made sense after I said "It's more like a jenga tower in zero G"

Regarding ascii: https://github.com/lewish/asciiflow / https://asciiflow.com

**Comment by joamatab** [comment]
yes, what you want to have is a `merge` function. We could add something like that in a `CellGroup`

How about adding a warning that states that connect does not imply that ports will remain connected?

**Comment by sebastian-goeldi** [comment]
I think we should leve the deprecation warning and that it does not imply a cell connection, but keep connect in the near future (let's say 6month+). I am totally fine with that. And yes, that functionality is something desired. I think we should go a step further with it though. It shouldn't matter with which part you start to build, as long as the graph is the same (and an anchor is defined, otherwise default to lower left corner of the cell). I think this should be not that hard to implement, but will take some time.

**Comment by tvt173** [comment]
hmm... i'm not sure if I fully agree with the discussion on the ideal behavior of `connect`...

i think "connect" has different implications in a layout vs logical context. in a logical (schematic) context, you of course expect things to remain connected once you have connected them. but in a layout context, cells and shapes are independent entities until we have grouped them into a cell... at which case the cell is it's own reference plane with all internal relations frozen. if we add persistent relations like this, but outside of the context of a cell, it should require some extra concept of grouping which will also add more complexity. i'm not sure I agree it's necessary. why not just group things into a cell once you want to fix their relations?

i can see the point that `connect` is not the clearest term though vs `mate` or (i'd also suggest) `abut`. but i'd also suggest against changing the names of key functions like this unless absolutely necessary. if we do change, it definitely needs a long deprecation window, as discussed.

**Comment by amccaugh** [comment]
A couple of comments:

* I think whether `connect` means permanently-connect or one-off-connect is a matter of opinion, and either interpretation makes sense to me.  Honestly, looking back at the work in phidl, I kind of wish I had gone with the term `mate` instead of `connect`, just because that's likely closer to the defacto standard in most CAD software (SolidWorks, AutoCAD, etc).  But there's a lot of room here -- I've thought about adding exactly this functionality to phidl, and when I did I mostly envisioned it being under the term `bind`.  That said, I definitely understand the Lego-block idea that `connect` can literally mean that things are connected in some kind of semipermanent way.  To the point @tvt173 made though, generally these operations are fairly atomic -- one has to answer, how important is it that function at the pcell-level, or even at higher levels?  Does it merit its own term/verb, or can it be an argument?  `connect(A,B, permanently_join_forever = True)` (terrible naming deliberate but you get the idea)
* I have to strongly object against the term `align`.  The term "align" has a long history of usage in vector-editing software and it effectively means "move one or more objects so one part of them touches an axis", and only in very specific cases does it mean "move two objects together so they're touching and rotate them so two faces/edges meet exactly", which is the action we're talking about in this context.  See for example [Illustrator](https://www.youtube.com/watch?v=kOQ0fnOtkXY&t=1s), [Inkscape](https://inkscape-manuals.readthedocs.io/en/latest/align-and-distribute.html), or [AutoCAD](https://www.youtube.com/watch?v=lpMNUuKMlCU), or [KLayout](https://www.klayout.de/doc/manual/object_align.html) itself.  Even outside that context, if one was asked to align dinner plates on a table, it wouldn't imply pushing the plates together and making them all contiguous 😄

**Comment by sebastian-goeldi** [comment]
If [align](https://help.autodesk.com/view/ACD/2022/ENU/index.html?guid=GUID-D0FA10D5-76EE-4B80-A285-43C7F39916DB) in autocad isn't exactly what connecting ports is doing, I am not sure what is. It is lierally described as tacking two points and move & rotate one to fit both points of two objects together. Do I now seriously have to rewrite the connect function to use two edges instead of using one transformation of each instance, just to prove my point?

But, maybe I should change ports and just make them images, then maybe align is the proper [term](https://klayout.org/downloads/master/doc-qt5/manual/landmarks.html)?

**Comment by tvt173** [comment]
technically when we connect, I would say we "abut", we don't align.

if you would tell me you are "aligning two ports" i would expect the resultant port vectors to point in the same direction. however, when we connect, the two ports face each other (they are 180 deg separated). so i don't think "align" is a good term

**Comment by sebastian-goeldi** [comment]
Again, I am fine using something else (that doesn't have a meaning of two becoming one joined thing in its [first](https://www.merriam-webster.com/dictionary/connect) definition or two), but as a non-native English speaker I have to say "abut" is about the last thing I will look for in an API documentation. Initially I was looking into overloading `transform` but that will be too much of a hassle. So, by all means, I am open for other suggestions.

**Comment by gdspaul** [comment]
The top illustration of "align" in the autocad doc<https://help.autodesk.com/view/ACD/2022/ENU/index.html?guid=GUID-D0FA10D5-76EE-4B80-A285-43C7F39916DB> could have been drawn for kfactory align I think.  I don't like the powerpoint connotation particularly but if it's in autocad then there's an excellent precedent.
[cid:5861696a-d92d-45b9-bed2-e7db7ea71690]
________________________________

**Comment by tvt173** [comment]
from the autocad example, i'd only argue that the conventions are different... they are taking a sequence of points and aligning them (here too, I would say "mating" is probably a better term, but I won't argue 😄 ). at least in gdsfactory, we consider a port to be primarily a vector (with the location and orientation of the port). so I think of these terms relative to that vector. which is why "align" sounds confusing/contradictory to me. i see this is a ticket for kfactory though, and not gdsfactory, so it's hard for me to be insistent on _changing_ the syntax in kfactory, I am only insistent on _not changing_ it for gdsfactory. so my comments are only relevant if we wish to "align" 😉 the terminology between the two (sorry for the pun...)

**Comment by sebastian-goeldi** [comment]
Yes, but whether to represent the port as a full transformation (x,y,angle,mirror) and width, or whether you do so as an edge has the same exact geometric information. You can also represent the port as two points, it will just make the transformation calculation in KLayout more complicated, but the information is the same, so imo it's exactly the same as the autocad align. Also with regards to ms office: It is the same operation, just limited to x or y or both

**Comment by Ealameda31** [comment]
I would strong oppose `connect`. Why can't we use something like:

* Align
* Arrange
* Attune

**Comment by amccaugh** [comment]
That's interesting, I had a very different interpretation of what AutoCAD's `align` is doing at that link.  To me, there's no connotation of something akin to a "port" on an object being used, but I guess if you interpret the port as two endpoints that can make sense.

Ultimately though, I think what is most important is answering the question "What is the most common name for this usage pattern that's already in existence"?  Because for better or worse, convention >> accuracy, otherwise you end up with goofy, stratified standards reminiscent of [this](https://xkcd.com/927/).  Something I got a lot of insight out during phidl's design was building little tables like this:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/2075083/236850962-aad0e6f9-8f26-4508-afb3-60b501903964.png">

From this I eventually (and somewhat painfully) ended up renaming `reflect` to `mirror` in phidl because it was the clear winner in GDSII-land.  For `offset`, there wasn't really a clear winner so I broke the tie by justifying it as (1) underlying Clipper library was using the term `offset`, and (2) in most math/algorithm contexts that I saw the term was also `offset`

**Comment by HelgeGehring** [comment]
Why do we need this function at all?

Can't we just use

```ref1['o1']=ref['o2']```

This would imply, that `ref1` needs to be aligned. Just changing the port without moving the reference doesn't make sense anyway, so we don't lose any functionality.

**Comment by sebastian-goeldi** [comment]
> Why do we need this function at all?
> 
> Can't we just use
> 
> ```ref1['o1']=ref['o2']```
> 
> This would imply, that `ref1` needs to be aligned. Just changing the port without moving the reference doesn't make sense anyway, so we don't lose any functionality. 

I actually like this one, but maybe a different operator?

I would suggest `ref1.ports[portname] | port`

And allow a `port` to mirror with `~port`. So that you can do `ref1.ports[portname] | ~port`

**Comment by HelgeGehring** [comment]
hmm, when I see `|` I directly think of `or`. In this case after the "assignment" they would be the same, so `=` somehow makes sense. But yeah, I see the possible source of confusion :D

Maybe we could meet at `|=`? :D

But I'd guess if we don't go for `=` my favorite  `<=`, it would make a difference and clearly show the direction of the assignment

I really like mirroring a port with an operator! From vector-calculations I'd somehow expect a `-`, would you have a reason to prefer `~`?

About `.ports`, is there any reason to not directly have the ports available via `ref[name]` ? I'd guess that's by far the most used field of the reference, so there should be a shortcut (and always writing `.port` annoyed me a lot :D )

**Comment by sebastian-goeldi** [comment]
I like `<=`, no objection there, I was thinking of `|` because both ports form a line at the junction if you were to draw athem out, just want to avoid `__eq__` due to potential confusion (especially when dealing with KLayout where you have the differentiation between `const` objects vs dynamic ones). `-` (as in the `__neg__` one) is fine by me. My suggestion then is `-` becomes inversion of mirror flag and `~` rotation by 180 degrees?

hm, there is no direct reason for instances. There is one for KCells (although it is not a super strong argument). It will confusing when using mypy. `__getitem__` gets you named references. I would like to adhere somewhat to the "be expressive with python code" paradigm, so I suggest either we make a fast access or we go one step further (and this might solve the "I am a lonely lonely port with no parent")

We could do:

```
# access a port
ref @ portname
# connect ports
ref @ portname >> ref @ portname
```

I think here `>>` would be preferable because we are doing the inverse when we are adding a reference instance, because we are moving the reference instance on the left side

**Comment by joamatab** [comment]
something that would be great is to expose the ports as instance attributes

```
bend['o1'] >> wg['o2']
```

which is equivalent to `bend.connect('o1', wg['o2']`

or even nicer (with autocomplete enabled) would be

```
bend.o1 >> wg.o2
```

what do you think?

**Comment by sebastian-goeldi** [comment]
This would completely wreck mypy, so I am tending towards no. Mypy can't dynamically check attributes, unless they have one type.

**Comment by joamatab** [comment]
`bend.port.o1 >> wg.port.o2` would be even better

**Comment by tvt173** [comment]
I'll give my arguments against operator overloading as this is _by far_ my least favorite option...
1. They're usually obscure and hard to understand on first glance. `bend.port.o1 >> wg.port.o2` makes no sense to me without further context.
2. Then, if you don't know what they are, they're much harder to look up than regular functions. Not only will it be more difficult to search the docs for, but you also usually won't get tooltips in your IDE explaining the operator in the same way that you would with a function.
3. They're much harder to refactor than regular functions. Say if you want to change this again... It's much easier to rename a function than it is to change something that was written with an operator to a function call instead (or vice versa). That was one of the main justifications I remember as to why the `print` function syntax was changed between python 2 and 3... it is much easier to refactor `print('message')` to `log('message')` rather than refactoring from the oddly formed `print 'message'` when you decide you want to log the message instead

**Comment by joamatab** [comment]
how about using `bend.transport('o1', wg['o2'])`?

**Comment by tvt173** [comment]
good enough for me! (I'm exhausted of debating names and that one's fun and interesting 😄)

**Comment by gdspaul** [comment]
Transport doesn't have any connotation of a relation between objects. If i see port.transport() or cell.transport() I'm not going to guess why the argument is another port (unless i start thinking of shipping objects between seaports perhaps, which isn't quite right). transport() avoids the faults of other specific ideas like align() because it's more vague.

I'll toss another few ideas out there.

abut()
Two things that lie next to each other and share an edge or corner abut each other.  This word is used for property lines, a real world example of being adjacent without being stuck together.  It's a little bit grammatically weird since it doesn't mean "move".  But the result is very clear, possibly clearer even than align().

appose()
This is the best one i could find.  It means to place things side by side.  The similarity to "oppose" gives it a suggestion of the 180 degree angle between ports (though linguistically false).

align_to()
Tossing this out as an example of how prepositions might improve clarity.

Sent from my iPhone

On May 12, 2023, at 1:42 AM, sebastian-goeldi ***@***.******@***.***>> wrote:


[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

Yeah, it's unique for sure. So it goes a bit against what @amccaugh<https://github.com/amccaugh> said (and I generally absolutely agree with that), but:

It lines up super well with the fact that klayout is below.

  *   The explanation is intuitive if we go by "imaging it by transporting the instance from port a to b"
  *   trans(form)port
  *   it pops up for autocomplete along with all the standard (klayout) options for moving (trans/transform)

So, I am very much in favor of this solution.

**Comment by joamatab** [comment]
`abut` also sounds good to me,

how about just using `wg.move('o1', bend['o2'])` ? in the end we are just moving an instance to match another port

**Comment by gdspaul** [comment]
Honestly I like this one a lot.  It might seem weird that move() also involves rotation.  But it’s extremely clear.

From: Joaquin Matres ***@***.***>
Date: Friday, May 12, 2023 at 8:19 AM
To: gdsfactory/kfactory ***@***.***>
Cc: Paul Hansen ***@***.***>, Mention ***@***.***>
Subject: Re: [gdsfactory/kfactory] improve names (Issue #97)

[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

abut also sounds good to me,

how about just using wg.move('o1', bend['o2']) ? in the end we are just moving an instance to match another port

**Comment by sebastian-goeldi** [comment]
My beef with `move` is simple: I already implemented the `instance.move((x1,y1), (x2,y2))` due to this https://github.com/gdsfactory/kfactory/issues/92 .  So if we add this into move, the annotations will become super complicated again. So the decision is simple for that one: Kick out the standard move (also from the UMInstance) or use another name.

![image](https://github.com/gdsfactory/kfactory/assets/44963764/018d2b59-23c2-4f00-b29f-15adb303b251)

**Comment by gdspaul** [comment]
I don't see it in the linked issue.  Wrong link?

Sent from my iPhone

On May 12, 2023, at 8:56 AM, sebastian-goeldi ***@***.******@***.***>> wrote:


[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

My beef with move is simple: I already implemented the instance.move((x1,y1), (x2,y2)) due to this #92<https://github.com/gdsfactory/kfactory/issues/92> . So if we add this into move, the annotations will become super complicated again. So the decision is simple for that one: Kick out the standard move (also from the UMInstance) or use another name.

[image]<https://user-images.githubusercontent.com/44963764/238021512-018d2b59-23c2-4f00-b29f-15adb303b251.png>

**Comment by sebastian-goeldi** [comment]
Well, it's not written in there, but the conversion from gdsfactory functions to kfactory is where it's coming from.  The code is here https://github.com/gdsfactory/kfactory/blob/f40c2c7d97bacd5ee3e7ce81287034b9880348c5/src/kfactory/kcell.py#L1943

**Comment by sebastian-goeldi** [comment]
:shrug: I don't have a preference for this one. This code piece is not yet in a release, so we can still remove it (only slightly intentional pun).

One mote though

`move((x,y),(x2,y2))` in kfactory can be done by simply doing `transform(kf.kdb.Trans(destination_point-origin_point)`

**Comment by gdspaul** [comment]
Yeah.  Do we actually _need_ this `move((x,y), (x2,y2))` function?  Most of the time people are probably using `numpy` anyway and `move(xy1 - xy0)` seems like the natural way to do this.

**Comment by sebastian-goeldi** [comment]
It doesn't matter which one you need or don't need. I don't want a dual purpose `move` or even confusion with `movex/y`. And the port one is very different from the current `move(x/y)`. It will make the API hard af to read and interpret. So either we drop all current moves in favor of the port transformation function or keep the current ones. All move are available with `transform(kdb.(D)Trans(x,y))`. So I am ok with dropping the moves.

**Comment by gdspaul** [comment]
Ok let me recap.  The choice is one of the following:
- `move(x,y)` or whatever—syntactic sugar for `transform(kdb.Trans(x,y))`
- `move` for ports
and specifically we do NOT do
- overload `move` for Cartesian translations and also for port "aligning"
- 
In that case `move(x,y)` absolutely wins IMO.  It's the more fundamental use case and it leads to a very natural API.

**Comment by sebastian-goeldi** [comment]
I don't know what to do now. I am good with almost anything. But if we go back to the gdsfactory `connect` we need very good documentation especially considering that there will be an "on-the-fly" netlist. So unless someone makes a PR with a renaming with good docs and explanation, I am putting this on the backburner and will see in the future when we have a better plan.
